ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Walker"
ENT.Author 			= "Warkin and An average Beanmann"
ENT.Purpose 		= "The pestilance spreads."
ENT.Instructions 	= "Click on the spawnicon to spawn it."