ENT.Base 			= "npc_vj_piv_walker_base_m"
ENT.Type 			= "ai"
ENT.PrintName 		= "Resistance Walker (Male)"
ENT.Author 			= "Warkin"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."