ENT.Base 			= "npc_vj_piv_fat_walker_m"
ENT.Type 			= "ai"
ENT.PrintName 		= "Bloated Runner (Male)"
ENT.Author 			= "Warkin"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."